# Special resource group name mapping.
# This mapping is used to convert the resource group name in the ARN to the Cloud Control API type name format.
# details in https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html
special_resource_group_name_mapping = {
    'ec2': 'EC2',
    's3': 'S3',
    'vpc': 'VPC',
    'rds': 'RDS',
    'sqs': 'SQS',
    'ssm': 'SSM',
    'sns': 'SNS',
    'iam': 'IAM',
    'kms': 'KMS',
    'acl': 'ACL',
    'ecr': 'ECR',
    'mfa': 'MFA',
    'ce': 'CE',
    'ecs': 'ECS',
    'eks': 'EKS',
    'iot': 'IoT',
    'ses': 'SES',
    'ds': 'DirectoryService',
    'mq': 'AmazonMQ',
    'cert': 'Certificate',
    'states': 'StepFunctions',
    'directory': 'SimpleAD',
    'statemachine': 'StateMachine',
    'es': 'OpenSearchService',
    'cognito-identity': 'Cognito',
    'cognito-idp': 'Cognito',
    'userpool': 'UserPool',
    'servicecatalog': 'ServiceCatalogAppRegistry',
    'identitypool': 'IdentityPool',
    'kafka': 'MSK',
    'identity': 'EmailIdentity',
    'elasticfilesystem': 'EFS',
    'codeartifact': 'CodeArtifact',
    'guardduty': 'GuardDuty',
    'identitypool': 'IdentityPool',
    'elasticbeanstalk': 'ElasticBeanstalk',
    'thingtype': 'ThingType',
    'cloudtrail': 'CloudTrail',
    'wafv2': 'WAFv2',
    'webacl': 'WebACL',
    'fleet': 'EC2Fleet',
    'replicaset': 'ReplicaSet',
    'natgateway': 'NatGateway',
    'apigateway': 'ApiGateway',
    'vpn-connection': 'VPNConnection',
    'restapis': 'RestApi',
    'apis': 'RestApi',
    'cloudformation': 'CloudFormation',
    'stackset': 'StackSet',
    'cloudwatch': 'CloudWatch',
    'elasticloadbalancing': 'ElasticLoadBalancingV2',
    'vpc-flow-log': 'FlowLog',
    'secretsmanager': 'SecretsManager',
    'loadbalancer': 'LoadBalancer',
    'targetgroup': 'TargetGroup',
    'subgrp': 'DBSubnetGroup',
    'elastic-ip': 'EIP',
    'acm': 'CertificateManager',
    'applications': 'Application',
    'attribute-groups': 'AttributeGroup',
    'autoscaling': 'AutoScaling',
    'autoscalinggroup': 'AutoScalingGroup',
    'elasticache': 'ElastiCache',
    'memorydb': 'MemoryDB',
    'parametergroup': 'ParameterGroup',
    'mfa': 'VirtualMFADevice',
    'datacatalog': 'DataCatalog',
    'apprunner': 'AppRunner',
    'autoscalingconfiguration': 'AutoScalingConfiguration',
    'dynamodb': 'DynamoDB',
    'db': 'DBInstance',
    'workgroup': 'WorkGroup',
    'firehose': 'KinesisFirehose',
    'deliverystream': 'DeliveryStream',
    'og': 'OptionGroup',
    'pg': 'DBParameterGroup',
    'anomalymonitor': 'AnomalyMonitor',
    'schemas': 'EventSchemas',
    'hostedzone': 'HostedZone',
    'healthcheck': 'HealthCheck',
    'anomalysubscription': 'AnomalySubscription',
    'saml-provider': 'SAMLProvider',
    'oidc-provider': 'OIDCProvider',
    'vpc-endpoint': 'VPCEndpoint',
    'cloudfront': 'CloudFront',
    'vpn-gateway': 'VPNGateway',
    'subnetgroup': 'SubnetGroup',
    'applicationversion': 'ApplicationVersion',
    'dhcp-options': 'DHCPOptions'
}

service_to_resource_group_name_mapping = {
    'S3': 'Bucket',
    'SQS': 'Queue'
}

blacklist_resource_types = [
    'acm:certificate',
    'iam:policy',
    'es:domain',
    'ec2:security-group-rule',
    'elasticloadbalancing:listener/net',
    'elasticloadbalancing:listener/app',
    'ssm:managed-instance',
    'ec2:spot-instances-request',
    'ec2:snapshot',
    'ec2:image',
    'rds:snapshot',
    'rds:secgrp',
    'ec2:reserved-instances',
    'ec2:client-vpn-endpoint',
    'rds:auto-backup',
    'rds:ri',
    'wafv2:webacl',
    'transfer:user',
    'iot:thingtype',
    'eks:*',
    'cloud9:*'
]

whitelist_resource_types = ["*"]

#whitelist_resource_types = [
#    'ec2:instance',
#    'rds:db',
#    'dynamodb:table',
#    's3:bucket',
#    'sqs:queue'
#]